# Generated by Django 3.2.9 on 2021-12-15 07:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20211215_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(max_length=200, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9]+@(gmail|email|outlook|ctdtechs)+.(com|edu|net)$')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=20, null=True, validators=[django.core.validators.RegexValidator('^(0|91)?[6789][0-9]{9}$')]),
        ),
    ]
