# Generated by Django 3.2.9 on 2021-12-15 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20211215_1302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='nickname',
        ),
    ]
