# Generated by Django 3.2.9 on 2022-01-06 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_customer_firstname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='firstname',
        ),
    ]
